### ISSUE TITLE
Add templates that works with the JPA EntityManager too

### ISSUE THREAD

**Issue by vladmihalcea** [hibernate/hibernate-test-case-templates#2]
We need to support both the Hibernate-specific API and Java Persistence API as well. This way, each issue can be represented exactly how the reporter has bumped into it. 

In the test cases that I run for my book, I already have this functionality: 

https://github.com/vladmihalcea/high-performance-java-persistence/blob/master/core/src/test/java/com/vladmihalcea/book/hpjp/util/AbstractTest.java

Although I combined both in one base class, which I then extend for each use case, we can have separate templates for Hibernate and JPA.

**Comment by vladmihalcea** [comment]
We already have this feature, I also added the transaction callback utilities in my fork:

- This is a [JPA test case](https://github.com/vladmihalcea/hibernate-orm/commit/977918ff4aaa2fa37f88c6063ba077aff8959644#diff-91549e6e7d65dbb404ea5b037cf55dd9)
- And this are [the transaction utilities](https://github.com/vladmihalcea/hibernate-orm/blob/feature/asciidocs/hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/util/TransactionUtil.java)

**Comment by gunnarmorling** [comment]
Anything you want to add or can we close this one now that your PR is merged?

**Comment by vladmihalcea** [comment]
From my point of view, I'll leave it like that.
Although I wished I could sneak in the Session and Transaction handling logic with lambdas, I'll let it go and use it only in the docs.
It's better to keep it simple here.
I'll write a blog post about this tomorrow.
