### ISSUE TITLE
Add more instructions on how to use the templates

### ISSUE THREAD

**Issue by gustavofcalmeida** [hibernate/hibernate-test-case-templates#20]
When we visit http://hibernate.org/orm/contribute/ the **Report/Investigate Bugs** section points to this repository.
Aside from this [README.md](https://github.com/hibernate/hibernate-test-case-templates/blob/master/orm/README.md) there is no much information on how to use the template. This is a problem for the less experienced like me and may prevent people from reporting bugs.
My suggestion is that you link this great [tutorial](http://in.relation.to/2016/01/14/hibernate-jpa-test-case-template/) in the README.md of the repository or in the **Report/Investigate Bugs** section.

**Comment by vladmihalcea** [comment]
Thanks for the suggestion. I [edited the REDAME file](https://github.com/hibernate/hibernate-test-case-templates/blob/master/orm/README.md) accordingly.
