### ISSUE TITLE
Auto-Detect Entities

### ISSUE THREAD

**Issue by geoffreywiseman** [hibernate/hibernate-test-case-templates#27]
Although the test case suggests that the project will automatically pick up new JPA entities, I had to add `<class>` nodes to the `persistence.xml` to have them picked up. I haven't used bare Hibernate (without Spring Boot) with JPA, so maybe I'm missing something about how this is supposed to work, but I cloned the project, added a `src/main/java`, and put my entities under there, and got this error:

Once I added the `<class>` nodes, everything was fine. Did I miss something?

```
java.lang.IllegalArgumentException: Unknown entity: org.hibernate.bugs.Application
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:807)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:788)
	at org.hibernate.bugs.JPAUnitTestCase.hhh123Test(JPAUnitTestCase.java:39)
```

**Comment by yrodiere** [comment]
Understanding your problem will be easier with the code. Please point us to your branch, or send a PR, so we can have a look?

**Comment by geoffreywiseman** [comment]
Sure, it was this fork:
https://github.com/geoffreywiseman/hibernate-test-case-templates

**Comment by yrodiere** [comment]
Your problem was that you defined the entities in your main code, but the `persistence.xml` in your tests.

If I remember correctly, Hibernate Search will only look for entities in the same JAR as the persistence.xml when performing classpath scanning.

So moving the persistence.xml to the main code fixes the problem: https://github.com/geoffreywiseman/hibernate-test-case-templates/pull/1
Alternatively, you can move the entities to the test code, which is generally what we do for test cases.

I will close this issue for now, feel free to reopen if my answer didn't help.

**Comment by geoffreywiseman** [comment]
Ok, I guess that makes some sense. Normally I'd expect tests to include and use the main classpath as well as their own classpath, but I don't know that much about how the Hibernate JPA scanning is written. It probably makes sense to compartmentalize somewhat in case you have multiple JPA-enabled JARs in a single classpath.  Anyway: might not be a terrible idea to suggest where you reference automation detection that the model will be automatically detected if it's placed in the `src/test`  package hierarchy, since that's where `persistence.xml` is found.

But thanks, I'll be better able to make a test case next time. ;)

**Comment by DonaldMaparura** [comment]
what if im using application.properties file how do l solve this error 
 Panache.getEntityManager().merge(products); is not picking my entity

**Comment by yrodiere** [comment]
@DonaldMaparura You seem to be using Quarkus. You'll have better answers if you ask the Quarkus community there: https://quarkus.io/community/ . When you ask them, provide the full stack trace, otherwise they are unlikely to understand what is going on.

**Comment by DonaldMaparura** [comment]
thanks ......coz l really have a tonne of questions
