### ISSUE TITLE
Version.java throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by manabsears** [hibernate/hibernate-test-case-templates#47]
I am using hibernate validator 5.2.2, and executing with Open JDK 11, on Windows 10.

This is code snippet from org.hibernate.validator.internal.util.Version.java

	public static int getJavaRelease() {
		// Will return something like 1.8
		String[] specificationVersion = System.getProperty( "java.specification.version" ).split( "\\." );

		return Integer.parseInt( specificationVersion[1] );
	}

Integer.parseInt( specificationVersion[1] ) => this line assumes the java.specification.version system property will always have two or more parts. But OpenJDK 11, on Windows10, returning just "11".

Because of this, this class throwing ArrayIndexOutOfBoundsException

**Comment by yrodiere** [comment]
Hi,

This GitHub repository is about providing test case templates for users to build reproducers of problems they are having. Issues reported here should be issues about the test case templates, not about Hibernate Validator.

Please report issues related to Hibernate Validator on JIRA: https://hibernate.atlassian.net/browse/HV

Though in this case, you won't need to. As indicated [here](https://hibernate.org/validator/releases/5.2/#compatibility), Hibernate Validator 5.2 only works with Java up to version 8. If you want to use Java 11, upgrade to a [more recent version of Hibernate Validator](https://hibernate.org/validator/releases/#compatibility-matrix) (preferably 6.2).

Closing. If you need more help, see https://hibernate.org/community/
